README.md

[Feature] Update README.md

---

GCR Project/File.cpp
GCR Project/File.h
GCR Project/main.cpp
UnitTest/File_Unittest.cpp
UnitTest/UnitTest.vcxproj.filters

File Class 기본 Interface 작성 및 Unit Test를 위한 파일 추가하였습니다.

[Feature] File I/F 및 Unit Test 기본 코드 추가

---

GCR Project/Parser.cpp
GCR Project/Parser.h

[Feature] Define Parser Interface

[Feature] Define Parser Interface

---

GCR Project/Parser.h

[bugfix] semiclone miss

---

GCR Project/GCR Project.vcxproj
GCR Project/GCR Project.vcxproj.filters

[Feature] Update vcproject files

---

GCR Project/File.cpp
GCR Project/File.h
GCR Project/main.cpp

File Class의 기본 동작을 위한 OpenFile, ReadLine(), WriteLine(), CloseFile(), IsValidFiles() method를 추가하였습니다.

[Feature] File Class의 I/F 동작 구현

---

GCR Project/EmployeeManager.cpp
GCR Project/EmployeeManager.h
UnitTest/EmployeeManager_Unittest2.cpp
UnitTest/UnitTest.vcxproj
UnitTest/UnitTest.vcxproj.filters

This commit also adds Search/Delete with no option function in EmployeeManager class.

[Feature] Add Unittest for EmployeeManager Search/Delete

---

UnitTest/File_Unittest.cpp

File Class의 기본 동작 확인을 위한 Unittest 구현 추가하였습니다.

[Test] File Class의 Unittest 코드 구현

---

GCR Project/Employee.h
GCR Project/EmployeeManager.cpp
UnitTest/EmployeeManager_Unittest2.cpp

remove mid phone number, last phone number, birth year, birth month

Refactor Employee struct

---

UnitTest/Parser_Unittest.cpp

[Test] Parser Unit Test

---

GCR Project/Parser.cpp
GCR Project/Parser.h

[Feature] Parser I/F Origin 입니다.

[Feature] Parser I/F Origin

---

GCR Project/Parser.cpp
GCR Project/Parser.h

[BUGFIX] Build Error (Parser)

---

GCR Project/Parser.cpp

[BUGFIX] Parser I/F Error fix

---

UnitTest/EmployeeManager_Unittest2.cpp
UnitTest/UnitTest.vcxproj
UnitTest/UnitTest.vcxproj.filters

EmployManager_Unittest2 파일의 Modify관련 함수 parameter 변경 적용
EmployManager Unittest files를 프로젝트 소스폴더에 추가

[Feature] Update EmployManager Unittest file

---

GCR Project/EmployeeManager.cpp
UnitTest/EmployeeManager_Unittest2.cpp

EmployManager_Unittest2의 모든 TC OK되도록 EmployManager의 Delete  operation 오류 수정
EmployManager_Unittest2의 잘못된 valid 조건 변경

[BugFix] Fix EmployMananger Delete operation

---

.gitignore

Add ignore file (*.txt for local output file)

[Feature] Update .gitignore

---

GCR Project/Parser.cpp
GCR Project/Parser.h
UnitTest/Parser_Unittest.cpp

Make output string부분에 말썽이 있어 빠르게 마무리하겠습니다.

[Feature] Parser I/F 구현 공유드립니다

---

GCR Project/EmployeeManager.cpp
GCR Project/EmployeeManager.h

한글 주석으로 인해 Build warning 발생하는 것 제거했습니다.

[Feature] Remove Build warnings (Remove KOREAN comment)

---

GCR Project/Parser.cpp
GCR Project/Parser.h
UnitTest/Parser_Unittest.cpp

Unit Test Bug FIx 입니다.
NULL -> ""

[Bugfix] Parser Unit test bug fix

---

UnitTest/Parser_Unittest.cpp

Unit Test Data Sample Bug fix 입니다.

[BUGFIX] Unit Test Data Error Fix

---

UnitTest/IntegrationTest.cpp
UnitTest/UnitTest.vcxproj
UnitTest/UnitTest.vcxproj.filters

제공된 input 기준으로 output이 동일한지 체크하는 testcase입니다.

[Test] Integration Test 추가

---

GCR Project/EmployeeManager.cpp

아마도 디버깅 중에 들어간 거 같은 로그 출력.. 삭제합니다.

[BugFix] Remove useless log print

---

GCR Project/Parser.cpp
UnitTest/Parser_Unittest.cpp

[BUGFIX]
Reverting String Slicer

[BUGFIX] Parser Revert

---

GCR Project/File.cpp
GCR Project/File.h
GCR Project/main.cpp
UnitTest/File_Unittest.cpp
UnitTest/IntegrationTest.cpp
UnitTest/Parser_Unittest.cpp

현재 구현된 UT의 Fail을 수정하였고,
clean code 관점에서 bopen 제거, security code 관점에서 output file의 기존 존재 여부를 확인하도록 기능 수정하였습니다.

Parse UT Fail 수정 및 File class에 clean code, security code 적용점 반영

---

GCR Project/Parser.cpp
GCR Project/common.cpp
GCR Project/common.h

Option function의 clean code 추가 진행 건입니다.

[Feature] Clean code for Option related function

---

GCR Project/EmployeeManager.cpp
GCR Project/EmployeeManager.h

EmployeeManager의 m_Results를 사용필요가 없기 때문에 삭제합니다.

[Feature][CleanCode] Remove m_Results in EmployeeManager

---

GCR Project/Employee.h
GCR Project/EmployeeManager.h
GCR Project/File.cpp
GCR Project/File.h
GCR Project/common.h

header에는 namespace 쓰지 않기
const 수식자 추가
불필요 주석 삭제
makeKeyValueFromString() 함수의 중복코드 삭제

[Feature][CleanCode] clean code 적용

---

GCR Project/refactoring_em.puml

발표 자료 작성시 class diagram 참조용으로 사용하면 될거 같습니다.

[Feature][UML] Update puml file

---

GCR Project/Option.cpp
GCR Project/Option.h
GCR Project/Parser.cpp
UnitTest/EmployeeManager_Unittest2.cpp
UnitTest/EmployeeManager_unittest_hm.cpp

Option Class 변경점으로 인해 Unit Test 빌드 안되는 부분을 수정하였습니다.
EmployeeManager UT는 양이 많아 상단 몇개만 수정해보았습니다.

[Refactoring] UnitTest Option class 사용부분 변경

---

UnitTest/EmployeeManager_unittest_hm.cpp

EmployeeManager Modify 부분 코드 수정

[REFACTORING]Option Refactoring 된 것에 맞춰

---

UnitTest/EmployeeManager_Unittest2.cpp

[Feature][Test] Fix EmployeeManager Unittest2

---

GCR Project/EmployeeManager.cpp
GCR Project/EmployeeManager.h

ISchOption* 로 casting 되는 부분을 제거하고 argument로 바꿨는데 
이렇게 수정하면 혹시 문제되는 부분 있는지 리뷰 부탁드립니다.

[REFACTORING] 중복된 casting을 제거하기 위해 ISchOption*로 argument 변경

---

GCR Project/EmployeeManager.cpp
GCR Project/EmployeeManager.h
GCR Project/Parser.cpp
GCR Project/Parser.h
UnitTest/EmployeeManager_Unittest2.cpp
UnitTest/EmployeeManager_unittest_hm.cpp

Unittest 오류는 수정 중입니다.
Integration test는 통과했습니다.

[Refactoring] EmployeeManager (search result 값복사 방지)

---

UnitTest/EmployeeManager_Unittest2.cpp

EmployeeManager_Unittest2 FAIL case 수정했습니다.

[FixBug] Fix EmployeeManager_Unittest2 FAIL case

---

UnitTest/IntegrationTest.cpp

- 시간 개선에 대해 평가 결과 : 7->6초로 1초 감소한 효과 있음

[Test] 시간 측정 TC 추가
